# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2aaf6994453e3085d3233fa7706d17b"
name = "aichatSh"
handle = "aichatsh"
application_url = "https://judicial-roles-upgrades-having.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = ["https://judicial-roles-upgrades-having.trycloudflare.com/auth/callback", "https://judicial-roles-upgrades-having.trycloudflare.com/auth/shopify/callback", "https://judicial-roles-upgrades-having.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
